sudo: required
services:
  - docker

before_install:
  - docker build -t dheeraj4v/multi-docker -f ./client/dockerfile.dev ./client

script:
  - docker run dheeraj4v/multi-docker npm test -- --coverage

after_success:
  - docker build -t dheeraj4v/multi-client ./client 
  - docker build -t dheeraj4v/multi-nginx ./nginx
  - docker build -t dheeraj4v/multi-server ./server
  - docker build -t dheeraj4v/multi-worker ./worker
  # ......
  - echo "$DOCKER_PASSWORD" | docker login -u "#DOCKER_ID" --password-stdin
  #...
  - docker push dheeraj4v/multi-client 
  - docker push dheeraj4v/multi-nginx
  - docker push dheeraj4v/multi-server
  - docker push dheeraj4v/multi-worker
